# Libraries

In [4]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from numpy.linalg import det, inv, pinv
from scipy.optimize import curve_fit
import seaborn as sns
from matplotlib import style
style.use('dark_background')

from sklearn.model_selection import train_test_split

In [2]:
directory = './samples/cribado/'
rgb = pd.read_csv(directory + 'RGB.csv', sep=';')
rgb2 = pd.read_csv(directory + 'RGB2.csv', sep=';')
xyz = pd.read_csv(directory + 'XYZ.csv', sep=';')
xyz2 = pd.read_csv(directory + 'XYZ2.csv', sep=';')

# Functions

In [3]:
def transform_matrix(df_input, df_output,intercept=True):
    X = df_input
    Y = df_output

    model = linear_model.LinearRegression(fit_intercept=intercept).fit(X,Y)
    A = model.coef_
    n = model.intercept_
    score = round(model.score(X, Y), 3)
        
    return np.array(A), np.array(n), np.array(score)

def multilineal_regressor(v_input, matrix):
    X = v_input.T
    A = matrix
    try:  
        Y =  inv(A.T.dot(A)).dot(A.T).dot(X)
    except:
        Y = pinv(A.T.dot(A)).dot(A.T).dot(X)
    return Y

def plot_prediction_error(sample, reference, prediction):
    figure_size = (4,3)
    fig = plt.figure(figsize=figure_size)
    plt.xlabel('sample')
    plt.ylabel(f'intensity')
    plt.plot(sample, label='sample', color='red')
    plt.plot(reference, label='reference', color='lime')
    plt.plot(prediction, label='prediction', color='yellow')
    plt.hlines(0, 0, len(reference))
    plt.legend()

    plt.figure(figsize=figure_size)
    #plt.title(''.join(reference.columns.tolist()) + f' - {coord}')
    plt.xlabel('reference')
    plt.ylabel('prediction')
    plt.scatter(reference, prediction, color='yellow')
    plt.plot(reference, reference, color='lime')
    plt.xlim(min(min(reference), min(prediction)),
             max(max(reference), max(prediction)))
    plt.ylim(min(min(reference), min(prediction)),
             max(max(reference), max(prediction)))
    
    plt.figure(figsize=figure_size)
    #plt.title(''.join(reference.columns.tolist()) + f' - {coord}')
    plt.xlabel('reference')
    plt.ylabel('sample')
    plt.scatter(reference, sample, color='red')
    plt.plot(reference, reference, color='lime')
    plt.xlim(min(min(reference), min(sample)),
             max(max(reference), max(sample)))
    plt.ylim(min(min(reference), min(sample)),
             max(max(reference), max(sample)))
    

# Results

In [5]:
X = rgb
y = rgb2

X_train, X_test, y_train, y_test = train_test_split(X, y)

## RGB' - RGB

In [13]:
A, n, score_rgb = transform_matrix(rgb, rgb2, intercept=True)
display(A, n, score_rgb)

array([[ 0.79553585,  0.15532704, -0.10468706],
       [ 0.07567958,  0.66599249,  0.0896365 ],
       [ 0.08361469,  0.07184519,  0.6855309 ]])

array([ 2.20742999,  3.90622131, -0.98832055])

array(0.988)

## XYZ'-XYZ

In [7]:
B, m, score_xyz = transform_matrix(xyz, xyz2, intercept=False)
display(B, m, score_xyz)

array([[ 0.60958399,  0.11571535, -0.02536082],
       [ 0.05774262,  0.61133833,  0.03391357],
       [ 0.05868707,  0.03982702,  0.58136542]])

array(0.)

array(0.993)

In [8]:
v = B.dot(xyz.T).T
xyz_predictions = pd.DataFrame(v, columns=['X', 'Y', 'Z'])
display(xyz_predictions, xyz, xyz2)
display((xyz_predictions.to_numpy()-xyz2.to_numpy())/xyz2.to_numpy()*100)

X         Y         Z
0   0.433948  0.458731  0.259177
1   0.431377  0.430977  0.259029
2   0.419979  0.425849  0.182125
3   0.592523  0.616403  0.480131
4   0.278282  0.283978  0.200513
5   0.264246  0.280101  0.136121
6   0.419852  0.384423  0.113956
7   0.293989  0.197649  0.074811
8   0.163247  0.091935  0.026941
9   0.154525  0.087108  0.026558
10  0.108827  0.061520  0.021263
11  0.057626  0.032939  0.013691
12  0.039521  0.023604  0.019759
13  0.025882  0.019343  0.024615
14  0.070619  0.048735  0.030776
15  0.085473  0.049507  0.023580
16  0.332169  0.282212  0.193295
17  0.141901  0.085409  0.030333
18  0.333855  0.256812  0.199425
19  0.441887  0.387745  0.397056
20  0.292355  0.190354  0.116469
21  0.250521  0.143022  0.070115
22  0.317602  0.233548  0.112147
23  0.205895  0.117328  0.057796
24  0.179529  0.101583  0.037959
25  0.168939  0.147196  0.212492
26  0.131700  0.083113  0.047755
27  0.314265  0.217921  0.267126
28  0.054730  0.032588  0.035326
29  0.177696  0.164800  0.307375
30  0.149498  0.094235  0.159962
31  0.047517  0.032731  0.045205
32  0.151298  0.110298  0.203151
33  0.254680  0.245083  0.283480
34  0.249432  0.154185  0.176838
35  0.057342  0.067339  0.162201
36  0.022045  0.023808  0.089276
37  0.167650  0.185832  0.299698
38  0.024266  0.025362  0.094645
39  0.113545  0.129176  0.257828
40  0.219333  0.256857  0.409646
41  0.101794  0.139603  0.138109
42  0.082372  0.125679  0.047175
43  0.064775  0.093345  0.034151
44  0.065260  0.077078  0.040924
45  0.174109  0.255362  0.072932
46  0.478469  0.547769  0.464369
47  0.039560  0.050318  0.034570
48  0.258261  0.300845  0.230247
49  0.029838  0.032177  0.021056
50  0.107599  0.158707  0.111560
51  0.115197  0.147819  0.053909
52  0.322370  0.392118  0.475155
53  0.061855  0.079819  0.076259
54  0.114050  0.169035  0.111299
55  0.309893  0.328998  0.363101
56  0.163360  0.178647  0.182848
57  0.008051  0.008924  0.014915

X         Y         Z
0   0.597839  0.675087  0.339210
1   0.602448  0.629117  0.341639
2   0.578133  0.630233  0.211736
3   0.831010  0.892023  0.680871
4   0.389778  0.412319  0.277306
5   0.361821  0.414615  0.169211
6   0.584985  0.568130  0.098041
7   0.432092  0.278833  0.065961
8   0.244312  0.126586  0.013006
9   0.231329  0.119854  0.014120
10  0.163094  0.084433  0.014327
11  0.086468  0.045062  0.011734
12  0.059921  0.031521  0.025779
13  0.039061  0.025920  0.036620
14  0.104558  0.067748  0.037741
15  0.128341  0.067584  0.022975
16  0.479249  0.402131  0.256557
17  0.211235  0.118495  0.022734
18  0.490753  0.358810  0.268909
19  0.646361  0.540993  0.580662
20  0.435515  0.262560  0.138387
21  0.376928  0.194506  0.069229
22  0.463236  0.331425  0.123435
23  0.309871  0.159479  0.057208
24  0.269287  0.139145  0.028577
25  0.252982  0.198777  0.326350
26  0.196606  0.114360  0.054462
27  0.476834  0.289709  0.391498
28  0.083740  0.042657  0.049389
29  0.270548  0.217028  0.486533
30  0.232855  0.118642  0.243515
31  0.072607  0.042939  0.067485
32  0.234637  0.140722  0.316112
33  0.370586  0.342219  0.426757
34  0.381274  0.202226  0.251834
35  0.088514  0.087139  0.264096
36  0.037151  0.027228  0.147948
37  0.246408  0.254451  0.473202
38  0.040833  0.028937  0.156694
39  0.170826  0.172174  0.414448
40  0.319569  0.354017  0.648115
41  0.137033  0.203777  0.209768
42  0.100923  0.192844  0.057746
43  0.080853  0.142789  0.040799
44  0.087491  0.114839  0.053694
45  0.214176  0.393214  0.076891
46  0.662009  0.795909  0.677404
47  0.052774  0.074603  0.049025
48  0.353808  0.440374  0.330161
49  0.041199  0.047143  0.028830
50  0.138137  0.237589  0.161673
51  0.148997  0.224264  0.062325
52  0.453440  0.557901  0.733316
53  0.084176  0.116249  0.114711
54  0.145525  0.253914  0.159360
55  0.442716  0.465947  0.547956
56  0.230925  0.255227  0.273718
57  0.011880  0.012164  0.023622

X         Y         Z
0   0.449433  0.474555  0.272310
1   0.434717  0.438083  0.260469
2   0.420037  0.416083  0.191616
3   0.627251  0.649743  0.515931
4   0.279657  0.281126  0.206919
5   0.260701  0.271578  0.144118
6   0.452521  0.398041  0.114558
7   0.305880  0.211835  0.073545
8   0.154794  0.086947  0.017361
9   0.138831  0.074681  0.014485
10  0.093754  0.048971  0.011318
11  0.060115  0.034519  0.016228
12  0.043109  0.027610  0.018576
13  0.029265  0.023850  0.022237
14  0.072165  0.052046  0.028382
15  0.079443  0.046890  0.016586
16  0.336942  0.289530  0.180207
17  0.127304  0.077985  0.024282
18  0.317750  0.243335  0.188970
19  0.460479  0.404099  0.397578
20  0.278895  0.183100  0.115613
21  0.251759  0.150919  0.073786
22  0.305008  0.222487  0.097335
23  0.184058  0.099152  0.047459
24  0.170528  0.099874  0.040442
25  0.162889  0.139150  0.218470
26  0.136905  0.089719  0.070584
27  0.310747  0.213501  0.272274
28  0.053573  0.029841  0.032145
29  0.176517  0.155595  0.317449
30  0.146323  0.087664  0.156180
31  0.031845  0.021033  0.034662
32  0.148566  0.102974  0.207483
33  0.258936  0.246987  0.287450
34  0.248717  0.149753  0.177059
35  0.060250  0.065843  0.153088
36  0.025138  0.024851  0.078702
37  0.165165  0.180123  0.295152
38  0.028853  0.024457  0.093451
39  0.114361  0.126566  0.256638
40  0.220378  0.257209  0.416032
41  0.090967  0.130846  0.119304
42  0.063121  0.101386  0.041780
43  0.048277  0.077328  0.026236
44  0.062947  0.071920  0.043424
45  0.148111  0.232902  0.059067
46  0.478975  0.556611  0.462531
47  0.039670  0.048250  0.032989
48  0.249933  0.294313  0.219571
49  0.030536  0.031488  0.021188
50  0.086421  0.151951  0.093206
51  0.103077  0.130644  0.055852
52  0.323884  0.408930  0.480114
53  0.049295  0.067798  0.057674
54  0.087371  0.151510  0.093036
55  0.289864  0.304501  0.337479
56  0.145704  0.156564  0.162110
57  0.014280  0.015241  0.019276

array([[-3.44529285e+00, -3.33444652e+00, -4.82275075e+00],
       [-7.68318941e-01, -1.62219230e+00, -5.52975591e-01],
       [-1.39205270e-02,  2.34706334e+00, -4.95299560e+00],
       [-5.53638653e+00, -5.13117347e+00, -6.93899555e+00],
       [-4.91915269e-01,  1.01457120e+00, -3.09580783e+00],
       [ 1.35994041e+00,  3.13835464e+00, -5.54897494e+00],
       [-7.21929193e+00, -3.42128191e+00, -5.25549436e-01],
       [-3.88747741e+00, -6.69698205e+00,  1.72140686e+00],
       [ 5.46114364e+00,  5.73787598e+00,  5.51807075e+01],
       [ 1.13046916e+01,  1.66396398e+01,  8.33554784e+01],
       [ 1.60773530e+01,  2.56254096e+01,  8.78714190e+01],
       [-4.13933518e+00, -4.57811221e+00, -1.56313410e+01],
       [-8.32438638e+00, -1.45083301e+01,  6.36754081e+00],
       [-1.15612715e+01, -1.88954367e+01,  1.06934338e+01],
       [-2.14288744e+00, -6.36306814e+00,  8.43183823e+00],
       [ 7.59001485e+00,  5.57969873e+00,  4.21719114e+01],
       [-1.41672786e+00, -2.52747252e+00

## XYZ - RGB

In [9]:
C, u, score = transform_matrix(rgb, xyz2, intercept=False)
display(C, u, score)

array([[ 9.02926432e-04,  8.98035945e-04, -1.63151807e-04],
       [ 4.78415469e-04,  1.36189658e-03, -1.61945168e-04],
       [-4.16120814e-05,  2.63353100e-04,  1.41215081e-03]])

array(0.)

array(0.818)

In [10]:
v = C.dot(rgb.T).T
tot_predictions = pd.DataFrame(v, columns=['X', 'Y', 'Z'])
display(tot_predictions, rgb, xyz2)
display((tot_predictions.to_numpy()-xyz2.to_numpy())/xyz2.to_numpy()*100)

X         Y         Z
0   0.373707  0.380753  0.243050
1   0.371475  0.367825  0.243405
2   0.379052  0.377594  0.186380
3   0.413870  0.419429  0.337309
4   0.299972  0.300493  0.223697
5   0.304179  0.309945  0.173056
6   0.390005  0.370281  0.094098
7   0.297735  0.235196  0.090165
8   0.185168  0.101278 -0.000291
9   0.179674  0.097914  0.008389
10  0.151123  0.081221  0.022042
11  0.112869  0.061687  0.026919
12  0.091369  0.051368  0.058322
13  0.084213  0.066315  0.079402
14  0.148727  0.115787  0.077395
15  0.138541  0.080435  0.047534
16  0.322403  0.293186  0.210341
17  0.196603  0.134841  0.041544
18  0.311604  0.266632  0.212257
19  0.350348  0.323390  0.308768
20  0.278310  0.209328  0.145788
21  0.214924  0.115983  0.085239
22  0.314388  0.263907  0.139155
23  0.194253  0.101939  0.076545
24  0.187496  0.100247  0.041740
25  0.213800  0.194768  0.237053
26  0.189538  0.135770  0.089256
27  0.272258  0.209697  0.247439
28  0.099124  0.050498  0.083433
29  0.205831  0.195218  0.284807
30  0.157396  0.090850  0.189871
31  0.108032  0.078312  0.106702
32  0.182403  0.140917  0.225701
33  0.269501  0.261985  0.271773
34  0.221411  0.141603  0.192711
35  0.088548  0.110702  0.219570
36  0.031682  0.044000  0.163834
37  0.199133  0.215009  0.287420
38  0.040222  0.048298  0.167655
39  0.149247  0.168877  0.270068
40  0.218072  0.246930  0.332700
41  0.145880  0.191399  0.204192
42  0.124536  0.187448  0.101842
43  0.139646  0.178413  0.082409
44  0.154860  0.168280  0.101201
45  0.226214  0.288606  0.090528
46  0.364958  0.391666  0.340359
47  0.112343  0.130613  0.099385
48  0.279878  0.303117  0.246355
49  0.104802  0.108181  0.073363
50  0.126339  0.194884  0.182671
51  0.204718  0.232516  0.100466
52  0.275247  0.314721  0.354406
53  0.128368  0.154259  0.152499
54  0.131155  0.202018  0.181163
55  0.293328  0.302415  0.307420
56  0.220749  0.231557  0.225229
57  0.039055  0.043218  0.066032

R    G    B
0   222  218  138
1   233  205  141
2   231  208  100
3   253  243  201
4   186  171  132
5   179  176   95
6   252  188   39
7   248   92   54
8   202    4    5
9   197    4   11
10  168    3   20
11  125    4   22
12  102    7   43
13   74   29   53
14  128   46   50
15  149   11   36
16  232  149  128
17  186   37   28
18  244  126  134
19  252  172  194
20  248   78   96
21  242    8   66
22  247  117   84
23  222    4   60
24  210    4   35
25  160  105  153
26  176   45   60
27  244   88  166
28  118    3   62
29  149  113  185
30  179   20  136
31  103   30   73
32  167   63  153
33  181  149  170
34  231   39  136
35   40   84  141
36   15   40  109
37  115  139  181
38   25   40  112
39   81  116  172
40  114  166  208
41   45  139  120
42    6  141   46
43   41  121   37
44   80  102   55
45   64  193   30
46  201  241  202
47   50   85   56
48  150  187  144
49   61   63   42
50    6  153  101
51   92  144   47
52  136  209  216
53   54  105   90
54    6  158   99
55  178  182  189
56  129  141  137
57   22   29   42

X         Y         Z
0   0.449433  0.474555  0.272310
1   0.434717  0.438083  0.260469
2   0.420037  0.416083  0.191616
3   0.627251  0.649743  0.515931
4   0.279657  0.281126  0.206919
5   0.260701  0.271578  0.144118
6   0.452521  0.398041  0.114558
7   0.305880  0.211835  0.073545
8   0.154794  0.086947  0.017361
9   0.138831  0.074681  0.014485
10  0.093754  0.048971  0.011318
11  0.060115  0.034519  0.016228
12  0.043109  0.027610  0.018576
13  0.029265  0.023850  0.022237
14  0.072165  0.052046  0.028382
15  0.079443  0.046890  0.016586
16  0.336942  0.289530  0.180207
17  0.127304  0.077985  0.024282
18  0.317750  0.243335  0.188970
19  0.460479  0.404099  0.397578
20  0.278895  0.183100  0.115613
21  0.251759  0.150919  0.073786
22  0.305008  0.222487  0.097335
23  0.184058  0.099152  0.047459
24  0.170528  0.099874  0.040442
25  0.162889  0.139150  0.218470
26  0.136905  0.089719  0.070584
27  0.310747  0.213501  0.272274
28  0.053573  0.029841  0.032145
29  0.176517  0.155595  0.317449
30  0.146323  0.087664  0.156180
31  0.031845  0.021033  0.034662
32  0.148566  0.102974  0.207483
33  0.258936  0.246987  0.287450
34  0.248717  0.149753  0.177059
35  0.060250  0.065843  0.153088
36  0.025138  0.024851  0.078702
37  0.165165  0.180123  0.295152
38  0.028853  0.024457  0.093451
39  0.114361  0.126566  0.256638
40  0.220378  0.257209  0.416032
41  0.090967  0.130846  0.119304
42  0.063121  0.101386  0.041780
43  0.048277  0.077328  0.026236
44  0.062947  0.071920  0.043424
45  0.148111  0.232902  0.059067
46  0.478975  0.556611  0.462531
47  0.039670  0.048250  0.032989
48  0.249933  0.294313  0.219571
49  0.030536  0.031488  0.021188
50  0.086421  0.151951  0.093206
51  0.103077  0.130644  0.055852
52  0.323884  0.408930  0.480114
53  0.049295  0.067798  0.057674
54  0.087371  0.151510  0.093036
55  0.289864  0.304501  0.337479
56  0.145704  0.156564  0.162110
57  0.014280  0.015241  0.019276

array([[-1.68492720e+01, -1.97662687e+01, -1.07451508e+01],
       [-1.45478660e+01, -1.60375560e+01, -6.55135256e+00],
       [-9.75741311e+00, -9.25039396e+00, -2.73230731e+00],
       [-3.40184493e+01, -3.54469064e+01, -3.46213020e+01],
       [ 7.26433742e+00,  6.88917559e+00,  8.10896033e+00],
       [ 1.66773129e+01,  1.41275100e+01,  2.00794254e+01],
       [-1.38150084e+01, -6.97412796e+00, -1.78596308e+01],
       [-2.66282079e+00,  1.10280654e+01,  2.25986320e+01],
       [ 1.96221814e+01,  1.64827824e+01, -1.01678913e+02],
       [ 2.94193043e+01,  3.11098550e+01, -4.20797402e+01],
       [ 6.11915316e+01,  6.58532221e+01,  9.47526392e+01],
       [ 8.77559019e+01,  7.87020783e+01,  6.58847208e+01],
       [ 1.11948682e+02,  8.60506911e+01,  2.13957469e+02],
       [ 1.87756303e+02,  1.78053179e+02,  2.57075849e+02],
       [ 1.06091229e+02,  1.22469668e+02,  1.72687912e+02],
       [ 7.43907750e+01,  7.15380183e+01,  1.86594807e+02],
       [-4.31516083e+00,  1.26278490e+00